remote_theme: pages-themes/hacker@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one

title: Cipher Podliq
description:  I’m an Offensive Security Researcher specializing in malware development. With a strong background in Python and Rust programming, HackTheBox, and other cool stuff. In my blog I will explore even the smallest gap in the vast sea of the Internet. Follow along as I share insights and tutorials from my learning process.
